import type { Metadata } from "next";
import Header from "@/components/header/header";
import { FiltroProvider } from "@/contexts/FiltroContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="bg-orange-200">
      <body>
        <FiltroProvider>
          <Header />
          <main>{children}</main>
        </FiltroProvider>
      </body>
    </html>
  );
}
